"use client";

import React from "react";
import { Oswald, Inter } from "next/font/google";
import { ArrowLeft, Shield, Eye, ShieldAlert, BadgeInfo, Landmark } from "lucide-react";
import Link from "next/link";

const oswald = Oswald({ subsets: ["latin"], weight: "700" });
const inter = Inter({ subsets: ["latin"] });

export default function PrivacyPage() {
  return (
    <div className={`min-h-screen bg-gray-50 text-black py-12 px-6 ${inter.className}`}>
      <div className="max-w-3xl mx-auto">
        
        {/* Back Link */}
        <Link href="/" className="inline-flex items-center gap-2 font-bold uppercase text-xs hover:text-yellow-600 mb-8 transition">
          <ArrowLeft size={16} /> Back to Homepage
        </Link>

        {/* Title Card */}
        <div className="bg-white border-4 border-black p-8 rounded-3xl shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] mb-10">
          <div className="flex items-center gap-4 mb-4">
            <div className="bg-yellow-400 p-3 rounded-2xl border-2 border-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]">
              <Shield size={32} />
            </div>
            <div>
              <h1 className={`text-4xl md:text-5xl uppercase leading-none ${oswald.className}`}>Privacy & Policies</h1>
              <p className="text-xs font-bold text-gray-500 uppercase tracking-widest mt-1">DPDPA, GDPR, CCPA & Refund Disclosures</p>
            </div>
          </div>
        </div>

        {/* Policy Contents */}
        <div className="bg-white border-2 border-black rounded-3xl p-8 md:p-12 space-y-10 shadow-sm">
          
          {/* Section 1: Privacy Policy */}
          <section className="space-y-4">
            <h2 className="text-2xl font-black uppercase flex items-center gap-2 pb-2 border-b-2 border-black">
              <span className="bg-yellow-400 px-2 py-0.5 border border-black rounded text-xs">1</span>
              Privacy Policy
            </h2>
            <p className="text-sm text-gray-600 font-medium leading-relaxed">
              At Pixorva, we value your privacy and are committed to protecting your personal data in accordance with global regulations including the India Digital Personal Data Protection Act (DPDPA), the EU General Data Protection Regulation (GDPR), and the California Consumer Privacy Act (CCPA).
            </p>
            <div className="space-y-3">
              <h3 className="text-base font-bold uppercase text-gray-800">A. Data We Collect</h3>
              <p className="text-xs text-gray-500 leading-relaxed">
                We collect account details (email, full name), payment billing details, user prompts/inputs, uploaded files/code inside the File Vault, session cookie preferences, and usage telemetries (API hits, model latency, and browser metadata).
              </p>
              
              <h3 className="text-base font-bold uppercase text-gray-800">B. Data Retention & Sub-processors</h3>
              <p className="text-xs text-gray-500 leading-relaxed">
                We store database records on cloud servers (Supabase / AWS) for as long as your account remains active. We share necessary billing details with our payment gateway (Razorpay) and invoke third-party AI models (e.g. OpenAI, Anthropic, Google Gemini APIs) to run active workspace agents. Prompts sent to APIs are not utilized for training foundation models.
              </p>
              
              <h3 className="text-base font-bold uppercase text-gray-800">C. Your Privacy Rights</h3>
              <p className="text-xs text-gray-500 leading-relaxed">
                Under GDPR and DPDPA, you hold the right to access your stored data archive, rectify inaccuracies, revoke consent, and request complete account/data erasure. You can trigger data downloads and account erasure directly within your Settings Dashboard.
              </p>
            </div>
          </section>

          {/* Section 2: Acceptable Use Policy */}
          <section className="space-y-4">
            <h2 className="text-2xl font-black uppercase flex items-center gap-2 pb-2 border-b-2 border-black">
              <span className="bg-yellow-400 px-2 py-0.5 border border-black rounded text-xs">2</span>
              AI Acceptable Use Policy (AUP)
            </h2>
            <p className="text-sm text-gray-600 font-medium leading-relaxed">
              Pixorva serves as a platform orchestrating autonomous agent behaviors. The output generated by AI models is probabilistic.
            </p>
            <ul className="list-disc pl-6 text-xs text-gray-500 space-y-2">
              <li><strong>Prohibited Actions:</strong> You may not use Pixorva to deploy malware, generate hate speech, scrape proprietary websites without consent, automate harassment campaigns, or deceive users by claiming autonomous agents are real humans.</li>
              <li><strong>Model Output Disclaimers:</strong> Pixorva does not accept liability for autonomous agent actions, code bugs generated by developer agents, or financial errors introduced by automated analysts. Verify outputs manually before deployment.</li>
            </ul>
          </section>

          {/* Section 3: Billing, Refund & Cancellations */}
          <section className="space-y-4">
            <h2 className="text-2xl font-black uppercase flex items-center gap-2 pb-2 border-b-2 border-black">
              <span className="bg-yellow-400 px-2 py-0.5 border border-black rounded text-xs">3</span>
              Refund, Billing & Cancellation Policy
            </h2>
            <div className="space-y-3 text-xs text-gray-500 leading-relaxed font-medium">
              <p>
                <strong>Billing Cycle:</strong> All bundle plans (Growth Pro, Enterprise) and active hired agents are billed monthly recurring. Payments are processed securely via Razorpay UPI or Cards.
              </p>
              <p>
                <strong>Cancellations:</strong> You can cancel any subscription plan, Governance access, or individual employee contract at any time inside the <strong>Settings &rarr; Plan & Subscription Status</strong> dashboard. Upon cancellation, access remains active until the end of the current billing month, after which the slot or agent is deactivated.
              </p>
              <p>
                <strong>Refunds:</strong> Due to server provisioning and API model token expenses, we do not grant refunds for computational usage credits or monthly billing cycles already processed, except where mandated by local consumer protection statutes.
              </p>
            </div>
          </section>

          {/* Section 4: Cookie Policy */}
          <section className="space-y-4">
            <h2 className="text-2xl font-black uppercase flex items-center gap-2 pb-2 border-b-2 border-black">
              <span className="bg-yellow-400 px-2 py-0.5 border border-black rounded text-xs">4</span>
              Cookies & Tracking
            </h2>
            <p className="text-sm text-gray-600 font-medium leading-relaxed">
              We employ cookie identifiers to maintain authentication states, track user settings preferences, and perform website traffic analytics.
            </p>
            <div className="bg-gray-50 border border-gray-200 p-4 rounded-xl text-xs text-gray-500 font-mono space-y-1">
              <p>• <strong>sb-access-token / sb-refresh-token:</strong> Essential session cookies managing Supabase user login keys.</p>
              <p>• <strong>pixorva_cookie_consent:</strong> Functional cookie storing your accepted/declined privacy cookie configuration.</p>
            </div>
          </section>

          {/* Grievance officer segment */}
          <section className="space-y-3 pt-6 border-t-2 border-black border-dashed">
            <h2 className="text-2xl font-black uppercase flex items-center gap-2">
              <Landmark size={22} className="text-yellow-600" />
              Grievance Redressal Officer (DPDPA / India)
            </h2>
            <p className="text-sm text-gray-600 font-medium leading-relaxed">
              In accordance with the India Information Technology Act and the DPDPA, please direct queries or grievance filings to:
            </p>
            <div className="bg-yellow-50 border-2 border-black p-4 rounded-xl space-y-1.5 text-xs font-bold text-gray-800">
              <p>Attention: Grievance Redressal Officer</p>
              <p>Contact Person: Mr. Pranav Khandelwal</p>
              <p>Address: Jaipur, Rajasthan, India</p>
              <p>Email: <a href="mailto:grievance@pixorva.com" className="underline">grievance@pixorva.com</a> / <a href="mailto:privacy@pixorva.com" className="underline">privacy@pixorva.com</a></p>
            </div>
          </section>

        </div>
      </div>
    </div>
  );
}
